package com.bank.domain;

import java.util.Scanner;

public class Account {

	private int accId;
	private int balance;
	private int custId;
	
	public Account(int accId, int balance, int custId) {
		super();
		this.accId = accId;
		this.balance = balance;
		this.custId = custId;
	}
	
	// account ID is generated by sequence in DB
	public Account(int balance, int custId) {
		super();
		this.balance = balance;
		this.custId = custId;
	}

	@Override
	public String toString() {
		return "Account [balance=" + balance + ", custId=" + custId + "]";
	}
	
	public int getAccId() {
		return accId;
	}

	public void setAccId(int accId) {
		this.accId = accId;
	}

	public int getCustId() {
		return custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public void setBalance(int balance) {
		this.balance = balance;
	}

	public Account(){	//set balance to 0
		balance=0;
	}
	
	public void deposit(int amount){	//deposit
		balance=balance+amount;
	}
	
	public void withdraw(int amount){	//withdraw
		if(amount<=balance){
			balance=balance-amount;
		} 
		else{
			System.err.println("Insufficient funds.");
		}		
	}
	
	public int getBalance(){	//get balance
		return balance;
	}
}
