package com.bank.domain;

public class Customer {
	
	private int custId;
	private String custFirstName;
	private String custLastName;
	private String username;
	private String password;
	
	public Customer(int custId, String custFirstName, String custLastName, String username, String password) {
		super();
		this.custId = custId;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.username = username;
		this.password = password;
	}
	// customer ID is generated by sequence
	public Customer(String custFirstName, String custLastName, String username, String password) {
		super();
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.username = username;
		this.password = password;
	}
	
	@Override
	public String toString() {
		return "Customer [custId=" + custId + ", custFirstName=" + custFirstName + ", custLastName=" + custLastName
				+ ", username=" + username + ", password=" + password + "]";
	}
	public int getCustId() {
		return custId;
	}
	public void setCustId(int custId) {
		this.custId = custId;
	}
	public String getCustFirstName() {
		return custFirstName;
	}
	public void setCustFirstName(String custFirstName) {
		this.custFirstName = custFirstName;
	}
	public String getCustLastName() {
		return custLastName;
	}
	public void setCustLastName(String custLastName) {
		this.custLastName = custLastName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
}
