--------------------------------------------------------
--  File created - Friday-June-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALBUM
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."ALBUM" 
   (	"ALBUMID" NUMBER, 
	"TITLE" VARCHAR2(160 BYTE), 
	"ARTISTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTIST
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."ARTIST" 
   (	"ARTISTID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BEAR
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."BEAR" 
   (	"BEAR_ID" NUMBER(*,0), 
	"BEAR_TYPE_ID" NUMBER(*,0), 
	"BEAR_NAME" VARCHAR2(100 BYTE), 
	"BEAR_BIRTHDATE" DATE, 
	"BEAR_WEIGHT" NUMBER(*,0) DEFAULT 200, 
	"CAVE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BEAR_BEEHIVE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."BEAR_BEEHIVE" 
   (	"BEAR_ID" NUMBER(*,0), 
	"BEEHIVE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BEAR_TYPE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."BEAR_TYPE" 
   (	"BEAR_TYPE_ID" NUMBER(*,0), 
	"BEAR_TYPE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BEEHIVE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."BEEHIVE" 
   (	"BEEHIVE_ID" NUMBER(*,0), 
	"BEEHIVE_WEIGHT" NUMBER(*,0) DEFAULT 50
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAVE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."CAVE" 
   (	"CAVE_ID" NUMBER(*,0), 
	"CAVE_NAME" VARCHAR2(100 BYTE), 
	"MAX_BEARS" NUMBER(*,0) DEFAULT 4
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."CUSTOMER" 
   (	"CUSTOMERID" NUMBER, 
	"FIRSTNAME" VARCHAR2(40 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"COMPANY" VARCHAR2(80 BYTE), 
	"ADDRESS" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(40 BYTE), 
	"STATE" VARCHAR2(40 BYTE), 
	"COUNTRY" VARCHAR2(40 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(24 BYTE), 
	"FAX" VARCHAR2(24 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"SUPPORTREPID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."EMPLOYEE" 
   (	"EMPLOYEEID" NUMBER, 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"REPORTSTO" NUMBER, 
	"BIRTHDATE" DATE, 
	"HIREDATE" DATE, 
	"ADDRESS" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(40 BYTE), 
	"STATE" VARCHAR2(40 BYTE), 
	"COUNTRY" VARCHAR2(40 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(24 BYTE), 
	"FAX" VARCHAR2(24 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GENRE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."GENRE" 
   (	"GENREID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."INVOICE" 
   (	"INVOICEID" NUMBER, 
	"CUSTOMERID" NUMBER, 
	"INVOICEDATE" DATE, 
	"BILLINGADDRESS" VARCHAR2(70 BYTE), 
	"BILLINGCITY" VARCHAR2(40 BYTE), 
	"BILLINGSTATE" VARCHAR2(40 BYTE), 
	"BILLINGCOUNTRY" VARCHAR2(40 BYTE), 
	"BILLINGPOSTALCODE" VARCHAR2(10 BYTE), 
	"TOTAL" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICELINE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."INVOICELINE" 
   (	"INVOICELINEID" NUMBER, 
	"INVOICEID" NUMBER, 
	"TRACKID" NUMBER, 
	"UNITPRICE" NUMBER(10,2), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDIATYPE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."MEDIATYPE" 
   (	"MEDIATYPEID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYLIST
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."PLAYLIST" 
   (	"PLAYLISTID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYLISTTRACK
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."PLAYLISTTRACK" 
   (	"PLAYLISTID" NUMBER, 
	"TRACKID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRACK
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."TRACK" 
   (	"TRACKID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"ALBUMID" NUMBER, 
	"MEDIATYPEID" NUMBER, 
	"GENREID" NUMBER, 
	"COMPOSER" VARCHAR2(220 BYTE), 
	"MILLISECONDS" NUMBER, 
	"BYTES" NUMBER, 
	"UNITPRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SQ_BEAR_PK
--------------------------------------------------------

   CREATE SEQUENCE  "CHINOOK"."SQ_BEAR_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_BEAR_TYPE_PK
--------------------------------------------------------

   CREATE SEQUENCE  "CHINOOK"."SQ_BEAR_TYPE_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 81 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SQ_BEEHIVE_PK
--------------------------------------------------------

   CREATE SEQUENCE  "CHINOOK"."SQ_BEEHIVE_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
REM INSERTING into CHINOOK.BEAR
SET DEFINE OFF;
REM INSERTING into CHINOOK.BEAR_BEEHIVE
SET DEFINE OFF;
REM INSERTING into CHINOOK.BEAR_TYPE
SET DEFINE OFF;
Insert into CHINOOK.BEAR_TYPE (BEAR_TYPE_ID,BEAR_TYPE_NAME) values (1,'GRIZZLY');
Insert into CHINOOK.BEAR_TYPE (BEAR_TYPE_ID,BEAR_TYPE_NAME) values (2,'POLAR');
Insert into CHINOOK.BEAR_TYPE (BEAR_TYPE_ID,BEAR_TYPE_NAME) values (3,'PANDA');
REM INSERTING into CHINOOK.BEEHIVE
SET DEFINE OFF;
Insert into CHINOOK.BEEHIVE (BEEHIVE_ID,BEEHIVE_WEIGHT) values (1,50);
REM INSERTING into CHINOOK.CAVE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ALBUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_ALBUM" ON "CHINOOK"."ALBUM" ("ALBUMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ARTIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_ARTIST" ON "CHINOOK"."ARTIST" ("ARTISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CUSTOMER
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_CUSTOMER" ON "CHINOOK"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYEE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_EMPLOYEE" ON "CHINOOK"."EMPLOYEE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GENRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_GENRE" ON "CHINOOK"."GENRE" ("GENREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVOICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_INVOICE" ON "CHINOOK"."INVOICE" ("INVOICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVOICELINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_INVOICELINE" ON "CHINOOK"."INVOICELINE" ("INVOICELINEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEDIATYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_MEDIATYPE" ON "CHINOOK"."MEDIATYPE" ("MEDIATYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PLAYLIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_PLAYLIST" ON "CHINOOK"."PLAYLIST" ("PLAYLISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PLAYLISTTRACK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_PLAYLISTTRACK" ON "CHINOOK"."PLAYLISTTRACK" ("PLAYLISTID", "TRACKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRACK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_TRACK" ON "CHINOOK"."TRACK" ("TRACKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005155
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."SYS_C005155" ON "CHINOOK"."BEAR" ("BEAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005156
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."SYS_C005156" ON "CHINOOK"."BEAR_TYPE" ("BEAR_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005157
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."SYS_C005157" ON "CHINOOK"."CAVE" ("CAVE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005158
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."SYS_C005158" ON "CHINOOK"."BEEHIVE" ("BEEHIVE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005159
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."SYS_C005159" ON "CHINOOK"."BEAR_BEEHIVE" ("BEAR_ID", "BEEHIVE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_CAVE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."UQ_CAVE_NAME" ON "CHINOOK"."CAVE" ("CAVE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_TYPE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."UQ_TYPE_NAME" ON "CHINOOK"."BEAR_TYPE" ("BEAR_TYPE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_BEAR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."TR_INSERT_BEAR" 
BEFORE INSERT ON BEAR
FOR EACH ROW
BEGIN
  SELECT SQ_BEAR_PK.NEXTVAL INTO :NEW.BEAR_ID FROM DUAL;
  --DUAL IS A DUMMY TABLE. USE IT WHEN YOU DON'T REQUIRE A TABLE
  --BUT NEED TABLE-LIKE SYNTAX
END;
/
ALTER TRIGGER "CHINOOK"."TR_INSERT_BEAR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_BEAR_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."TR_INSERT_BEAR_TYPE" 
BEFORE INSERT ON BEAR_TYPE
FOR EACH ROW
BEGIN
  SELECT SQ_BEAR_TYPE_PK.NEXTVAL INTO :NEW.BEAR_TYPE_ID FROM DUAL;
  --DUAL IS A DUMMY TABLE. USE IT WHEN YOU DON'T REQUIRE A TABLE
  --BUT NEED TABLE-LIKE SYNTAX
END;
/
ALTER TRIGGER "CHINOOK"."TR_INSERT_BEAR_TYPE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_BEEHIVE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."TR_INSERT_BEEHIVE" 
BEFORE INSERT ON BEEHIVE
FOR EACH ROW
BEGIN
  SELECT SQ_BEEHIVE_PK.NEXTVAL INTO :NEW.BEEHIVE_ID FROM DUAL;
  --DUAL IS A DUMMY TABLE. USE IT WHEN YOU DON'T REQUIRE A TABLE
  --BUT NEED TABLE-LIKE SYNTAX
END;
/
ALTER TRIGGER "CHINOOK"."TR_INSERT_BEEHIVE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_CAVE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."TR_INSERT_CAVE" 
BEFORE INSERT ON CAVE
FOR EACH ROW
BEGIN
  SELECT SQ_CAVE_PK.NEXTVAL INTO :NEW.CAVE_ID FROM DUAL;
  --DUAL IS A DUMMY TABLE. USE IT WHEN YOU DON'T REQUIRE A TABLE
  --BUT NEED TABLE-LIKE SYNTAX
END;
/
ALTER TRIGGER "CHINOOK"."TR_INSERT_CAVE" ENABLE;
--------------------------------------------------------
--  DDL for Procedure GET_LASTNAME_FIRSTNAME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."GET_LASTNAME_FIRSTNAME" (S OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN S FOR 
  SELECT LASTNAME, FIRSTNAME FROM EMPLOYEE;
END;

DECLARE 
S SYS_REFCURSOR;
SOME_LASTNAME EMPLOYEE.LASTNAME%TYPE;
SOME_NAME EMPLOYEE.FIRSTNAME%TYPE;
BEGIN
GET_LASTNAME_FIRSTNAME(S);
  LOOP
    FETCH S INTO SOME_LASTNAME,SOME_NAME;
    EXIT WHEN S%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(SOME_LASTNAME||' LASTNAME, '||SOME_NAME||' IS FIRSTNAME');
  END LOOP;
  CLOSE S;
END;



SELECT * FROM CUSTOMER;
select * from INVOICE;

/
--------------------------------------------------------
--  DDL for Procedure GREETINGS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."GREETINGS" 
AS 
BEGIN 
   dbms_output.put_line('Hello World!'); 
END;

/
--------------------------------------------------------
--  DDL for Procedure NAMES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."NAMES" 
AS 
BEGIN 
SELECT "A1"."FIRSTNAME" "FIRSTNAME","A1"."LASTNAME" "LASTNAME" FROM "CHINOOK"."EMPLOYEE" "A1";
  -- dbms_output.put_line('Hello World!'); 
END; 

/
--------------------------------------------------------
--  DDL for Procedure UPDATEEMPLOYEEINFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."UPDATEEMPLOYEEINFO" (EMPID IN NUMBER,ADDRESS1 IN VARCHAR2, 
CITY1 IN VARCHAR2, STATE1 IN VARCHAR2, COUNTRY1 IN VARCHAR2, POSTALCODE1 IN VARCHAR2, PHONE1 IN VARCHAR2, FAX1 IN VARCHAR2, EMAIL1 VARCHAR2)
IS
BEGIN
UPDATE EMPLOYEE
SET ADDRESS = ADDRESS1
WHERE EMPLOYEEID =EMPID;

UPDATE EMPLOYEE
SET CITY = CITY1
WHERE EMPLOYEEID =EMPID;

UPDATE EMPLOYEE
SET STATE = STATE1
WHERE EMPLOYEEID =EMPID;

UPDATE EMPLOYEE
SET COUNTRY = COUNTRY1
WHERE EMPLOYEEID =EMPID;

UPDATE EMPLOYEE
SET POSTALCODE= POSTALCODE1
WHERE EMPLOYEEID =EMPID;

UPDATE EMPLOYEE
SET PHONE=PHONE1
WHERE EMPLOYEEID =EMPID;

UPDATE EMPLOYEE
SET FAX = FAX1
WHERE EMPLOYEEID =EMPID;


UPDATE EMPLOYEE
SET EMAIL= EMAIL1
WHERE EMPLOYEEID =EMPID;
END;

/
--------------------------------------------------------
--  DDL for Function AVG_INVOICED
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."AVG_INVOICED" 
RETURN NUMBER IS AVGTOL NUMBER;
BEGIN
    SELECT AVG(TOTAL) INTO AVGTOL FROM INVOICE;
    RETURN AVGTOL;
END;

/
--------------------------------------------------------
--  DDL for Function AVG_TOTAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."AVG_TOTAL" 
RETURN NUMBER IS AVGTOTALBILL NUMBER;
BEGIN
    SELECT AVG(TOTAL) INTO AVGTOTALBILL FROM INVOICE;
    RETURN AVGTOTALBILL;
END;

/
--------------------------------------------------------
--  DDL for Function CALLTIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."CALLTIME" 
RETURN TIMESTAMP
is
t1 TIMESTAMP;
BEGIN
t1 := TIMESTAMP;
return t1;
END;

/
--------------------------------------------------------
--  DDL for Function CHECKAGE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."CHECKAGE" 
RETURN NUMBER 
IS
A AGE;
BEGIN
SELECT * FROM EMPLOYEE;
END;

/
--------------------------------------------------------
--  DDL for Function FIND_TIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."FIND_TIME" 
--RETURNING DATATYPE TIMESTAMP TO REPRESENT TIME
RETURN TIMESTAMP IS CTIME TIMESTAMP;
BEGIN
--RETURNING THE LOACLTIMESTAMP FUNCTION INTO CTIME
  SELECT LOCALTIMESTAMP INTO CTIME FROM DUAL;
  RETURN CTIME;
END;

/
--------------------------------------------------------
--  DDL for Function GET_TIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."GET_TIME" 
RETURN TIMESTAMP
IS 
T TIMESTAMP;
BEGIN
   T := CURRENT_TIMESTAMP;
RETURN T;
END;

/
--------------------------------------------------------
--  DDL for Function TEST_CURSOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."TEST_CURSOR" 
            return sys_refcursor
            is
                    c_result sys_refcursor;
            begin
                    open c_result for
                    select * from dual;
                    return c_result;
            end;

/
--------------------------------------------------------
--  DDL for Function TIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."TIME" 
RETURN CURRENT_TIMESTAMP IS 
   
BEGIN
   RETURN TIME;
END;





/
--------------------------------------------------------
--  DDL for Function WHATTIME
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."WHATTIME" 
RETURN TIMESTAMP;
BEGIN
DBMS_OUTPUT.PUT_LINE(SYS.TIMESTAMP_TO_SCN);

END;


FUNCTION square (original NUMBER)   -- parameter list
    RETURN NUMBER                     -- RETURN clause
  AS
                                      -- Declarative part begins
    original_squared NUMBER;
  BEGIN                               -- Executable part begins
    original_squared := original * original;
    RETURN original_squared;          -- RETURN statement
  END;
BEGIN
  DBMS_OUTPUT.PUT_LINE(square(100));  -- invocation
END;

/
--------------------------------------------------------
--  Constraints for Table ALBUM
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."ALBUM" ADD CONSTRAINT "PK_ALBUM" PRIMARY KEY ("ALBUMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."ALBUM" MODIFY ("ARTISTID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."ALBUM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."ALBUM" MODIFY ("ALBUMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTIST
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."ARTIST" ADD CONSTRAINT "PK_ARTIST" PRIMARY KEY ("ARTISTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."ARTIST" MODIFY ("ARTISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BEAR
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."BEAR" ADD CONSTRAINT "CK_BEAR_WEIGHT_POSITIVE" CHECK (BEAR_WEIGHT > 0) ENABLE;
  ALTER TABLE "CHINOOK"."BEAR" ADD PRIMARY KEY ("BEAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BEAR_BEEHIVE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."BEAR_BEEHIVE" ADD PRIMARY KEY ("BEAR_ID", "BEEHIVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BEAR_TYPE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."BEAR_TYPE" ADD CONSTRAINT "UQ_TYPE_NAME" UNIQUE ("BEAR_TYPE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."BEAR_TYPE" ADD PRIMARY KEY ("BEAR_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BEEHIVE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."BEEHIVE" ADD CONSTRAINT "CK_HIVE_WEIGHT_POSITIVE" CHECK (BEEHIVE_WEIGHT > 0) ENABLE;
  ALTER TABLE "CHINOOK"."BEEHIVE" ADD PRIMARY KEY ("BEEHIVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAVE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."CAVE" ADD CONSTRAINT "UQ_CAVE_NAME" UNIQUE ("CAVE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."CAVE" ADD PRIMARY KEY ("CAVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."EMPLOYEE" ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."EMPLOYEE" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."EMPLOYEE" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."EMPLOYEE" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GENRE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY ("GENREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."GENRE" MODIFY ("GENREID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICE" ADD CONSTRAINT "PK_INVOICE" PRIMARY KEY ("INVOICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("INVOICEDATE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("INVOICEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICELINE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICELINE" ADD CONSTRAINT "PK_INVOICELINE" PRIMARY KEY ("INVOICELINEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("UNITPRICE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("TRACKID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("INVOICEID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("INVOICELINEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDIATYPE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."MEDIATYPE" ADD CONSTRAINT "PK_MEDIATYPE" PRIMARY KEY ("MEDIATYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."MEDIATYPE" MODIFY ("MEDIATYPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYLIST
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."PLAYLIST" ADD CONSTRAINT "PK_PLAYLIST" PRIMARY KEY ("PLAYLISTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."PLAYLIST" MODIFY ("PLAYLISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYLISTTRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" ADD CONSTRAINT "PK_PLAYLISTTRACK" PRIMARY KEY ("PLAYLISTID", "TRACKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" MODIFY ("TRACKID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" MODIFY ("PLAYLISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "PK_TRACK" PRIMARY KEY ("TRACKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("UNITPRICE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("MILLISECONDS" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("MEDIATYPEID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("TRACKID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALBUM
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."ALBUM" ADD CONSTRAINT "FK_ALBUMARTISTID" FOREIGN KEY ("ARTISTID")
	  REFERENCES "CHINOOK"."ARTIST" ("ARTISTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BEAR
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."BEAR" ADD CONSTRAINT "FK_BEAR_BEAR_TYPE" FOREIGN KEY ("BEAR_TYPE_ID")
	  REFERENCES "CHINOOK"."BEAR_TYPE" ("BEAR_TYPE_ID") ENABLE;
  ALTER TABLE "CHINOOK"."BEAR" ADD CONSTRAINT "FK_BEAR_CAVE" FOREIGN KEY ("CAVE_ID")
	  REFERENCES "CHINOOK"."CAVE" ("CAVE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BEAR_BEEHIVE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."BEAR_BEEHIVE" ADD CONSTRAINT "FK_BEAR_BEEHIVE_BEAR" FOREIGN KEY ("BEAR_ID")
	  REFERENCES "CHINOOK"."BEAR" ("BEAR_ID") ENABLE;
  ALTER TABLE "CHINOOK"."BEAR_BEEHIVE" ADD CONSTRAINT "FK_BEAR_BEEHIVE_BEEHIVE" FOREIGN KEY ("BEEHIVE_ID")
	  REFERENCES "CHINOOK"."BEEHIVE" ("BEEHIVE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."CUSTOMER" ADD CONSTRAINT "FK_CUSTOMERSUPPORTREPID" FOREIGN KEY ("SUPPORTREPID")
	  REFERENCES "CHINOOK"."EMPLOYEE" ("EMPLOYEEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."EMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEEREPORTSTO" FOREIGN KEY ("REPORTSTO")
	  REFERENCES "CHINOOK"."EMPLOYEE" ("EMPLOYEEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICELINE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICELINE" ADD CONSTRAINT "FK_INVOICELINEINVOICEID" FOREIGN KEY ("INVOICEID")
	  REFERENCES "CHINOOK"."INVOICE" ("INVOICEID") ENABLE;
  ALTER TABLE "CHINOOK"."INVOICELINE" ADD CONSTRAINT "FK_INVOICELINETRACKID" FOREIGN KEY ("TRACKID")
	  REFERENCES "CHINOOK"."TRACK" ("TRACKID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAYLISTTRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" ADD CONSTRAINT "FK_PLAYLISTTRACKPLAYLISTID" FOREIGN KEY ("PLAYLISTID")
	  REFERENCES "CHINOOK"."PLAYLIST" ("PLAYLISTID") ENABLE;
  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" ADD CONSTRAINT "FK_PLAYLISTTRACKTRACKID" FOREIGN KEY ("TRACKID")
	  REFERENCES "CHINOOK"."TRACK" ("TRACKID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "FK_TRACKALBUMID" FOREIGN KEY ("ALBUMID")
	  REFERENCES "CHINOOK"."ALBUM" ("ALBUMID") ENABLE;
  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "FK_TRACKGENREID" FOREIGN KEY ("GENREID")
	  REFERENCES "CHINOOK"."GENRE" ("GENREID") ENABLE;
  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "FK_TRACKMEDIATYPEID" FOREIGN KEY ("MEDIATYPEID")
	  REFERENCES "CHINOOK"."MEDIATYPE" ("MEDIATYPEID") ENABLE;
