/*DML EXAMPLES JUN 21*/

/*THIS IS DDL*/
CREATE TABLE PERSON (
  P_ID NUMBER PRIMARY KEY,
  P_NAME VARCHAR2(2000),
  P_AGE INTEGER,
  P_STATE VARCHAR2(2000)
);

/*ADDING SOME DATA!*/
INSERT INTO PERSON VALUES (1,'JOHN',24,'MISSISSIPPI');
INSERT INTO PERSON VALUES (2,'CHRISTIAN',22,'NEW JERSEY');
INSERT INTO PERSON VALUES (3,'LENNY',32,'CALIFORNIA');
INSERT INTO PERSON VALUES (4,'GEORGE',33,'CALIFORNIA');
INSERT INTO PERSON VALUES (5,'Katie',25,'KANSAS');

/*DQL QUERIES*/
SELECT * FROM PERSON;
SELECT P_ID, P_NAME FROM PERSON;

/*ALIAS: KEYWORD "AS" 
USEFUL FOR READABILITY, PULLING DATA FROM MULTIPLE TABLES,
SUBQUERY RESULTS*/
SELECT 'FIRST NAME',P_NAME FROM PERSON;
SELECT P_NAME AS FIRSTNAME, P_STATE FROM PERSON;

/*CAN USE +,-,*,/ ON NUMERIC DATATYPES, CONCAT CHARACTER DATA WITH + */
SELECT P_NAME AS FIRSTNAME, P_AGE*P_AGE AS AGESQUARED FROM PERSON;

/*GROUP BY: REDUCING ROWS TO DISTINCT VALUES*/
SELECT P_STATE FROM PERSON
GROUP BY P_STATE
ORDER BY P_STATE;

SELECT AVG(P_AGE),P_STATE
FROM PERSON
GROUP BY P_STATE;

/*AGGREGATE FUNCTIONS: PERFORMS OPERATION ON ENTIRE COLUMN
AVG,MIN,MAX,COUNT,SUM.... */

/*SCALAR FUNCTION: OPERATE ON INDIVIDUAL ENTRIES*/
INSERT INTO PERSON VALUES (6,'Peter',NULL,'TEXAS');
SELECT UPPER(P_NAME) 
FROM PERSON 
WHERE P_NAME='Peter';
SELECT NVL(P_AGE,0)FROM PERSON;

/*ORDER BY*/
SELECT * FROM PERSON ORDER BY P_AGE;
SELECT * FROM PERSON ORDER BY P_AGE DESC, P_STATE DESC;

INSERT INTO PERSON VALUES (7,'cHRIS',22,'NEW YORK');

/*WHERE VS HAVING*/
SELECT * FROM PERSON WHERE P_AGE > 29;
SELECT AVG(P_AGE),P_STATE
FROM PERSON
GROUP BY P_STATE
HAVING AVG(P_AGE)>=25
ORDER BY P_STATE;

/*JOINS!*/
CREATE TABLE DEPARTMENT (
D_ID INTEGER PRIMARY KEY,
D_NAME VARCHAR2(2000)
);
CREATE TABLE EMPLOYEE (
E_ID INTEGER PRIMARY KEY,
E_NAME VARCHAR2(2000),
D_ID INTEGER,
FOREIGN KEY (D_ID) REFERENCES DEPARTMENT(D_ID)
);
CREATE TABLE PHONE_NUMBERS(
P_ID INTEGER PRIMARY KEY,
P_NUMBER VARCHAR(10),
E_ID INTEGER,
FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID)
);
INSERT INTO DEPARTMENT(D_ID, D_NAME) VALUES (1,'TELEPATHY');
INSERT INTO DEPARTMENT(D_ID, D_NAME) VALUES (2,'FLYING');
INSERT INTO DEPARTMENT(D_ID, D_NAME) VALUES (3,'TELEPORTATION');
INSERT INTO EMPLOYEE(E_ID,E_NAME,D_ID) VALUES (10,'Kristen',1);
INSERT INTO EMPLOYEE(E_ID,E_NAME,D_ID) VALUES (20,'Lenny',1);
INSERT INTO EMPLOYEE(E_ID,E_NAME,D_ID) VALUES (30,'Josh',2);
INSERT INTO EMPLOYEE(E_ID,E_NAME,D_ID) VALUES (40,'John',2);
INSERT INTO EMPLOYEE(E_ID,E_NAME,D_ID) VALUES (50,'Jesus',2);
INSERT INTO EMPLOYEE(E_ID,E_NAME) VALUES (60,'Jackson');
INSERT INTO PHONE_NUMBERS(P_ID, P_NUMBER, E_ID) VALUES (100,'0000001111',10);
INSERT INTO PHONE_NUMBERS(P_ID, P_NUMBER, E_ID) VALUES (101,'0000002222',10);
INSERT INTO PHONE_NUMBERS(P_ID, P_NUMBER, E_ID) VALUES (102,'0000003333',20);

/*INNER JOIN*/
SELECT * 
FROM DEPARTMENT 
INNER JOIN EMPLOYEE ON EMPLOYEE.D_ID = DEPARTMENT.D_ID;

SELECT EMP.E_NAME AS EMPLOYEE_NAME,DEPT.D_NAME AS DEPT_NAME
FROM DEPARTMENT DEPT
INNER JOIN EMPLOYEE EMP
ON EMP.D_ID = DEPT.D_ID;

SELECT EMP.E_NAME AS EMPLOYEE_NAME,DEPT.D_NAME AS DEPT_NAME
FROM DEPARTMENT DEPT LEFT JOIN EMPLOYEE EMP
ON EMP.D_ID = DEPT.D_ID;

SELECT EMP.E_NAME AS EMPLOYEE_NAME,DEPT.D_NAME AS DEPT_NAME
FROM DEPARTMENT DEPT FULL JOIN EMPLOYEE EMP
ON EMP.D_ID = DEPT.D_ID;

SELECT EMP.E_NAME AS EMPLOYEE_NAME,DEPT.D_NAME AS DEPT_NAME
FROM DEPARTMENT DEPT FULL OUTER JOIN EMPLOYEE EMP
ON EMP.D_ID = DEPT.D_ID;

SELECT EMP.E_NAME AS EMPLOYEE_NAME,DEPT.D_NAME AS DEPT_NAME
FROM DEPARTMENT DEPT JOIN EMPLOYEE EMP
ON EMP.D_ID = DEPT.D_ID;

SELECT EMP.E_NAME AS EMPLOYEE_NAME,DEPT.D_NAME AS DEPT_NAME
FROM DEPARTMENT DEPT RIGHT JOIN EMPLOYEE EMP
ON EMP.D_ID = DEPT.D_ID;

/*JOIN ALL TABLES: EVERYONE IN TELEPATHY DEPT WITH A PHONE NUMBER*/
SELECT E_NAME PERSONNAME, P_NUMBER PHONENUM
FROM DEPARTMENT 
INNER JOIN EMPLOYEE ON EMPLOYEE.D_ID = DEPARTMENT.D_ID
INNER JOIN PHONE_NUMBERS ON PHONE_NUMBERS.E_ID = EMPLOYEE.E_ID
WHERE DEPARTMENT.D_NAME = 'TELEPATHY';

INSERT INTO PHONE_NUMBERS VALUES ('105',0000005555,40);

/*UNION, INTERSECT, MINUS*/
SELECT D_ID FROM DEPARTMENT
UNION
SELECT D_ID FROM EMPLOYEE;
SELECT D_ID,D_NAME FROM DEPARTMENT
UNION ALL
SELECT D_ID,'NAME OF DEPT' FROM EMPLOYEE;
SELECT D_ID FROM DEPARTMENT
INTERSECT
SELECT D_ID FROM EMPLOYEE;
SELECT D_ID FROM DEPARTMENT
MINUS
SELECT D_ID FROM EMPLOYEE;
