DROP TABLE TRANSACTION;
DROP TABLE ACCOUNT;
DROP TABLE USER_TABLE;
/

CREATE TABLE USER_TABLE
(  
    USER_ID        NUMBER  PRIMARY KEY,
    USER_USERNAME  VARCHAR2(200) UNIQUE, 
    USER_PASSWORD  VARCHAR2(200), 
    USER_EMAIL     VARCHAR2(200), 
    USER_ACTIVE    NUMBER DEFAULT 1
);
/
CREATE TABLE ACCOUNT
(  
    ACCOUNT_ID      NUMBER  PRIMARY KEY,
    USER_ID         NUMBER, 
    BALANCE         NUMBER DEFAULT 0,
    ACCOUNT_ACTIVE  NUMBER DEFAULT 1,
   
    CONSTRAINT FK_USER_ID
    FOREIGN KEY (USER_ID)
    REFERENCES USER_TABLE(USER_ID)
    ON DELETE SET NULL
); 
/
CREATE TABLE TRANSACTION 
(
    TRANSACTION_ID   NUMBER PRIMARY KEY,
    ACCOUNT_ID       NUMBER, 
    TRANSACTION_TYPE VARCHAR2(100), 
    TRANSACTION_AMT  NUMBER, 
    TRANSACTION_DATE DATE,
    
    CONSTRAINT FK_ACCOUNT_ID
    FOREIGN KEY (ACCOUNT_ID)
    REFERENCES ACCOUNT(ACCOUNT_ID)
    ON DELETE SET NULL
); 

/
CREATE SEQUENCE SQ_USER_ID_PK
START WITH 1
INCREMENT BY 1; 
/
CREATE SEQUENCE SQ_ACCOUNT_ID_PK
START WITH 1
INCREMENT BY 1; 
/
CREATE SEQUENCE SQ_TRANSACTION_ID_PK
START WITH 1
INCREMENT BY 1; 
/

CREATE OR REPLACE TRIGGER TR_INSERT_USER
BEFORE INSERT ON USER_TABLE
FOR EACH ROW
BEGIN
  SELECT SQ_USER_ID_PK.NEXTVAL INTO :NEW.USER_ID FROM DUAL; 
END;
/
CREATE OR REPLACE TRIGGER TR_INSERT_ACCOUNT
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
  SELECT SQ_ACCOUNT_ID_PK.NEXTVAL INTO :NEW.ACCOUNT_ID FROM DUAL;  
END;
/
CREATE OR REPLACE TRIGGER TR_INSERT_ACCOUNT_AFTER
AFTER INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
  INSERT INTO TRANSACTION(ACCOUNT_ID, TRANSACTION_TYPE, TRANSACTION_AMT, TRANSACTION_DATE)
  VALUES(:NEW.ACCOUNT_ID, 'ACCOUNT CREATED', 0, SYSDATE);  
  --WHEN NEW ACCOUNT CREATED, ADDED TO TRANSACTION LOG
END;
/
CREATE OR REPLACE TRIGGER TR_INSERT_TRANSACTION
BEFORE INSERT ON TRANSACTION
FOR EACH ROW
BEGIN
  SELECT SQ_TRANSACTION_ID_PK.NEXTVAL INTO :NEW.TRANSACTION_ID FROM DUAL; 
END;
/

--INSERT INTO USER_TABLE(USER_USERNAME, USER_PASSWORD, USER_EMAIL) VALUES('ronnnwu', '1234', '123@123.com');
--INSERT INTO ACCOUNT(USER_ID) VALUES(2);
