CREATE TABLE ERS_USERS (
U_ID NUMBER(*,0) PRIMARY KEY,
U_USERNAME VARCHAR2(40 BYTE),
U_PASSWORD VARCHAR2(40 BYTE),
U_FIRSTNAME VARCHAR2(30 BYTE),
U_LASTNAME VARCHAR2(30 BYTE),
U_EMAIL VARCHAR2(100 BYTE),
UR_ID NUMBER(*,0)
);

CREATE TABLE ERS_REIMBURSEMENTS (
R_ID NUMBER(*,0) PRIMARY KEY,
R_AMOUNT NUMBER(22,2),
R_DESCRIPTION VARCHAR2(100 BYTE),
R_RECEIPT BLOB,
R_SUBMITTED TIMESTAMP,
R_RESOLVED TIMESTAMP,
U_ID_AUTHOR NUMBER(*,0),
U_ID_RESOLVER NUMBER(*,0),
RT_TYPE NUMBER(*,0),
RT_STATUS NUMBER(*,0)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS (
RS_ID NUMBER(*,0) PRIMARY KEY,
RS_STATUS VARCHAR2(30 BYTE)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE (
RT_ID NUMBER(*,0) PRIMARY KEY,
RT_TYPE VARCHAR2(30 BYTE)
);

CREATE TABLE ERS_USER_ROLES (
UR_ID NUMBER(*,0) PRIMARY KEY,
UR_ROLE VARCHAR2(40 BYTE)
);

ALTER TABLE ERS_USERS
ADD CONSTRAINT FK_UR_ID FOREIGN KEY (UR_ID) REFERENCES ERS_USER_ROLES(UR_ID);

ALTER TABLE ERS_REIMBURSEMENTS
ADD CONSTRAINT FK_ID_AUTHOR FOREIGN KEY (U_ID_AUTHOR) REFERENCES ERS_USERS(U_ID);

ALTER TABLE ERS_REIMBURSEMENTS
ADD CONSTRAINT FK_ID_RESOLVER FOREIGN KEY (U_ID_RESOLVER) REFERENCES ERS_USERS(U_ID);

ALTER TABLE ERS_REIMBURSEMENTS
ADD CONSTRAINT FK_RT_STATUS FOREIGN KEY (RT_STATUS) REFERENCES ERS_REIMBURSEMENT_STATUS(RS_ID);

ALTER TABLE ERS_REIMBURSEMENTS
ADD CONSTRAINT FK_RT_TYPE FOREIGN KEY (RT_TYPE) REFERENCES ERS_REIMBURSEMENT_TYPE(RT_ID);

ALTER TABLE ERS_USERS
ADD CONSTRAINT UQ_USERNAME UNIQUE (U_USERNAME);

ALTER TABLE ERS_USERS
ADD CONSTRAINT UQ_EMAIL UNIQUE (U_EMAIL);

INSERT INTO ERS_REIMBURSEMENT_STATUS (RS_ID,RS_STATUS) VALUES (1,'APPROVED');
INSERT INTO ERS_REIMBURSEMENT_STATUS (RS_ID,RS_STATUS) VALUES (2,'DENIED');
INSERT INTO ERS_REIMBURSEMENT_STATUS (RS_ID,RS_STATUS) VALUES (3,'PENDING');
INSERT INTO ERS_REIMBURSEMENT_TYPE (RT_ID,RT_TYPE) VALUES (1,'BUSINESS EXPENSE');
INSERT INTO ERS_REIMBURSEMENT_TYPE (RT_ID,RT_TYPE) VALUES (2,'MEDICAL EXPENSE');
INSERT INTO ERS_REIMBURSEMENT_TYPE (RT_ID,RT_TYPE) VALUES (3,'TRAVEL EXPENSE');
INSERT INTO ERS_REIMBURSEMENT_TYPE (RT_ID,RT_TYPE) VALUES (4,'EDUCATIONAL EXPENSE');
INSERT INTO ERS_USER_ROLES (UR_ID,UR_ROLE) VALUES (1,'MANAGER');
INSERT INTO ERS_USER_ROLES (UR_ID,UR_ROLE) VALUES (2,'EMPLOYEE');
INSERT INTO ERS_USERS (U_ID,U_USERNAME,U_PASSWORD,U_FIRSTNAME,U_LASTNAME,U_EMAIL,UR_ID) VALUES (1,'Mr.Krabs','money','Mr','Krabs','Money@gmail.com',1);
INSERT INTO ERS_USERS (U_ID,U_USERNAME,U_PASSWORD,U_FIRSTNAME,U_LASTNAME,U_EMAIL,UR_ID) VALUES (2,'TheChef','square','Spongebob','Squarepants','Sponge@gmail.com',2);
INSERT INTO ERS_USERS (U_ID,U_USERNAME,U_PASSWORD,U_FIRSTNAME,U_LASTNAME,U_EMAIL,UR_ID) VALUES (3,'Squid','squids','Squidward','Tentacles','clarinetgod@gmail.com',2);
INSERT INTO ERS_USERS (U_ID,U_USERNAME,U_PASSWORD,U_FIRSTNAME,U_LASTNAME,U_EMAIL,UR_ID) VALUES (4,'Plankton','thebest','Sheldon','Plankton','RuleTheWorld@gmail.com',1);
INSERT INTO ERS_USERS (U_ID,U_USERNAME,U_PASSWORD,U_FIRSTNAME,U_LASTNAME,U_EMAIL,UR_ID) VALUES (5,'SandyC','squirrel','Sandy','Cheeks','karatee@gmail.com',2);
INSERT INTO ERS_USERS (U_ID,U_USERNAME,U_PASSWORD,U_FIRSTNAME,U_LASTNAME,U_EMAIL,UR_ID) VALUES (6,'Patrick','patrick','Patrick','Star','mynameisPatrick@gmail.com',2);

CREATE SEQUENCE SQ_USER_ID
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SQ_REIMBURSEMENT_ID
INCREMENT BY 1
START WITH 1;

CREATE OR REPLACE TRIGGER TR_INSERT_USER_ID
BEFORE INSERT ON ERS_USERS
FOR EACH ROW
BEGIN
SELECT SQ_USER_ID.NEXTVAL INTO :NEW.U_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_INSERT_REIMBURSEMENT_ID
BEFORE INSERT ON ERS_REIMBURSEMENTS
FOR EACH ROW
BEGIN
SELECT SQ_REIMBURSEMENT_ID.NEXTVAL INTO :NEW.R_ID FROM DUAL;
END;

commit;