
/*

    ASSUMING THERE IS ONLY ONE BEAR TABLE. I SETUP THE TRIGGER SO THAT
    WHEN THE FORGEIN KEY USAGE HAS REACHED THE MAX_BEARS, NO COMMIT

*/
CREATE OR REPLACE TRIGGER TR_INSERT_UPDATE_BEAR
BEFORE INSERT OR UPDATE ON BEAR
FOR EACH ROW
DECLARE 
    CONT INTEGER;
    MAXBEARS INTEGER;
BEGIN 
    SELECT COUNT(*) INTO CONT FROM BEAR WHERE BEAR.CAVE_ID = NEW.CAVE_ID;
    SELECT MAX_BEARS INTO MAXBEARS FROM CAVE WHERE CAVE.CAVE_ID = NEW.CAVE_ID;
    IF (CONT = MAXBEARS) THEN
        ROLLBACK;
    END IF; 
END;
/